<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>10</LangVersion>
    <RootNamespace>Svelto.ECS.MiniExamples.Turrets</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Video" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Physics" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Navigation" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Particles" Version="4.3.0.2507" />
    <PackageReference Include="Stride.UI" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Core.Assets.CompilerApp" Version="4.3.0.2507" IncludeAssets="build;buildTransitive" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnemiesLayer\EnemiesLayer.csproj" />
    <ProjectReference Include="..\PlayerLayer\PlayerLayer.csproj" />
    <ProjectReference Include="..\StrideLayer\StrideLayer.csproj" />
    <ProjectReference Include="..\..\packages\com.sebaslab.svelto.common\Svelto.Common\Svelto.Common.csproj" />
    <ProjectReference Include="..\..\packages\com.sebaslab.svelto.ecs\Svelto.ECS.csproj" />
  </ItemGroup>
</Project>
