using System;
using System.Collections.Generic;
using DBC.ECS;
using Svelto.ECS.Internal;

namespace Svelto.ECS
{
    public struct EntityStructInitializer
    {
        public EntityStructInitializer(EGID id, Dictionary<Type, ITypeSafeDictionary> current)
        {
            _current = current;
            _id      = id;
        }

        public void Init<T>(T initializer) where T: struct, IEntityStruct
        {
            Check.Require(_current.ContainsKey(typeof(T) ), 
                    "Entity to initialise not generated by the EntiyDescriptor");
            
            var typeSafeDictionary = (TypeSafeDictionary<T>) _current[typeof(T)];

            initializer.ID = _id;

            int count;
            typeSafeDictionary.GetValuesArray(out count)[typeSafeDictionary.FindElementIndex(_id.entityID)] = initializer;
        }

        readonly Dictionary<Type, ITypeSafeDictionary> _current;
        readonly EGID                                  _id;
    }
}