using System;
using System.Collections.Generic;
using Svelto.ECS.Internal;

namespace Svelto.ECS
{
    public struct EntityStructInitializer
    {
        public EntityStructInitializer(EGID id, Dictionary<Type, ITypeSafeDictionary> current)
        {
            _current = current;
            ID      = id;
        }
        
        public EGID ID { get; }

        public void Init<T>(ref T initializer) where T: struct, IEntityStruct
        {
            DBC.ECS.Check.Require(_current.ContainsKey(typeof(T) )== true, 
                    "Entity to initialise not generated by the EntiyDescriptor");
            
            var typeSafeDictionary = (TypeSafeDictionary<T>) _current[typeof(T)];

            initializer.ID = ID;

            int count;
            typeSafeDictionary.GetValuesArray(out count)[typeSafeDictionary.FindElementIndex(ID.entityID)] = initializer;
        }
        
        public void Init<T>(T initializer) where T: struct, IEntityStruct
        {
            Init(ref initializer);
        }

        readonly Dictionary<Type, ITypeSafeDictionary> _current;
    }
}