<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>10</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>TRACE;</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\com.sebaslab.svelto.common\Svelto.Common\Svelto.Common.csproj" />
    <ProjectReference Include="..\..\..\packages\com.sebaslab.svelto.ecs\Svelto.ECS.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.3.0.2507" />
  </ItemGroup>
</Project>
